image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "11.17-alpine3.16"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "postgres"

service:
  type: ClusterIP
  port: 5432

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

postgres:
  username: postgres
  password: postgres